// Static manifest of DB tables an editor can be granted write access to.
// One entry per table backing a real CRUD route (generic crud.ts factory or
// legacy hand-rolled routes) — add a line here whenever a new writable table
// route is added.
export const KNOWN_CRUD_TABLES: string[] = [
  // generic crud.ts-backed tables
  'admin',
  'admission_disclosure_categories',
  'athletic_content_blocks',
  'athletic_division_benchmarks',
  'athletic_sports',
  'athletic_summary',
  'audit_logs',
  'authentication',
  'cip_mapping',
  'costs_fetched',
  'earnings_against_courses_merged',
  'faculty_import',
  'generated_missing_earnings',
  'program_debt',
  'program_descriptions',
  'pseo_entities',
  'pseo_institute_level',
  'pseo_state_level',
  'school_descriptions',
  'staging_admissions_categories',
  'states',
  'temp_sat',
  'usd_apply_clicks',
  'usdreport_colleges',
  'usdreports',
  'usduser_deactivations',
  'usdusers',
  'usdusers_preferred_programs',
  'usdusers_preferred_states',
  'user_compare_history',
  'user_saved_colleges',
  'user_saved_programs',
  // legacy hand-rolled routes
  'academics',
  'admissions',
  'aid',
  'completion',
  'costs',
  'debt_income_ratio',
  'earnings',
  'earnings_against_courses',
  'net_price_private_income',
  'net_price_public_income',
  'programs',
  'repayment',
  'roi',
  'schools',
  'students',
  'users',
];
