export type RemixType = {
  title: string
  icon: string
}

export const remixData: RemixType[] = [
  { title: '4k', icon: 'ri-4k-line' },
  { title: 'Refresh', icon: 'ri-refresh-line' },
  { title: 'Add', icon: 'ri-add-line' },
  { title: 'Alarm', icon: 'ri-alarm-line' },
  { title: 'Apple', icon: 'ri-apple-line' },
  { title: 'Archive', icon: 'ri-archive-line' },
  { title: 'Arrow Down', icon: 'ri-arrow-down-line' },
  { title: 'Arrow Up', icon: 'ri-arrow-up-line' },
  { title: 'Play', icon: 'ri-play-line' },
  { title: 'Bank', icon: 'ri-bank-line' },
  { title: 'Battery', icon: 'ri-battery-line' },
  { title: 'Bell', icon: 'ri-bell-line' },
  { title: 'Book', icon: 'ri-book-line' },
  { title: 'Camera', icon: 'ri-camera-line' },
  { title: 'Cloud', icon: 'ri-cloud-line' },
  { title: 'Code', icon: 'ri-code-line' },
  { title: 'Computer', icon: 'ri-computer-line' },
  { title: 'Compass', icon: 'ri-compass-line' },
  { title: 'Contacts', icon: 'ri-contacts-line' },
  { title: 'Delete', icon: 'ri-delete-bin-line' },
  { title: 'Download', icon: 'ri-download-line' },
  { title: 'Edit', icon: 'ri-edit-line' },
  { title: 'Search', icon: 'ri-search-line' },
  { title: 'File', icon: 'ri-file-line' },
  { title: 'Filter', icon: 'ri-filter-line' },
  { title: 'Flag', icon: 'ri-flag-line' },
  { title: 'Folder', icon: 'ri-folder-line' },
  { title: 'Gift', icon: 'ri-gift-line' },
  { title: 'Home', icon: 'ri-home-line' },
  { title: 'Image', icon: 'ri-image-line' },
  { title: 'Input', icon: 'ri-input-method-line' },
  { title: 'Instagram', icon: 'ri-instagram-line' },
  { title: 'Settings', icon: 'ri-settings-line' },
  { title: 'Keyboard', icon: 'ri-keyboard-line' },
  { title: 'Lightbulb', icon: 'ri-lightbulb-line' },
  { title: 'Lock', icon: 'ri-lock-line' },
  { title: 'Logout', icon: 'ri-logout-box-line' },
  { title: 'Mail', icon: 'ri-mail-line' },
  { title: 'Map', icon: 'ri-map-pin-line' },
  { title: 'Message', icon: 'ri-message-line' },
  { title: 'More', icon: 'ri-more-line' },
  { title: 'Notification', icon: 'ri-notification-line' },
  { title: 'Shopping Cart', icon: 'ri-shopping-cart-line' },
  { title: 'Phone', icon: 'ri-phone-line' },
]
